import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { info, warn, error as logError } from "../output/logger.js";

const HOOK_MARKER = "# codegoat pre-commit hook";

const SUPPORTED_EXTS = new Set([
  ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
  ".py", ".go", ".rb", ".java", ".rs",
  ".c", ".h", ".cpp", ".hpp", ".cc", ".php",
]);

export interface HookOptions {
  failOn?: string;
  severity?: string;
}

export function generateHookScript(opts: HookOptions = {}): string {
  const failOn = opts.failOn ?? "warning";
  const severity = opts.severity ?? "info";
  return `#!/bin/sh
${HOOK_MARKER}
# Auto-generated by codegoat — do not edit manually
# To remove: codegoat hook uninstall

# Fast path: skip if no supported source files are staged
STAGED=$(git diff --cached --name-only --diff-filter=ACM)
if [ -z "$STAGED" ]; then
  exit 0
fi

# Check if any staged files have supported extensions
HAS_SUPPORTED=false
for f in $STAGED; do
  case "$f" in
    *.ts|*.tsx|*.js|*.jsx|*.mjs|*.cjs|*.py|*.go|*.rb|*.java|*.rs|*.c|*.h|*.cpp|*.hpp|*.cc|*.php|*.kt|*.swift|*.scala)
      HAS_SUPPORTED=true
      break
      ;;
  esac
done

if [ "$HAS_SUPPORTED" = false ]; then
  exit 0
fi

# Run codegoat review on staged changes
echo "🐐 codegoat: reviewing staged changes..."
npx codegoat review . --diff --quiet --severity ${severity} --fail-on ${failOn}
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo ""
  echo "🐐 codegoat found issues. Fix them or commit with --no-verify to skip."
fi

exit $EXIT_CODE
`;
}

export function findGitRoot(from?: string): string | null {
  try {
    const root = execSync("git rev-parse --show-toplevel", {
      cwd: from ?? process.cwd(),
      encoding: "utf-8",
      stdio: ["pipe", "pipe", "pipe"],
    }).trim();
    return root;
  } catch {
    return null;
  }
}

export function getHookPath(gitRoot: string): string {
  // Check for husky
  const huskyDir = path.join(gitRoot, ".husky");
  if (fs.existsSync(huskyDir)) {
    return path.join(huskyDir, "pre-commit");
  }
  return path.join(gitRoot, ".git", "hooks", "pre-commit");
}

export function isCodegoatHook(hookPath: string): boolean {
  if (!fs.existsSync(hookPath)) return false;
  const content = fs.readFileSync(hookPath, "utf-8");
  return content.includes(HOOK_MARKER);
}

export function installHook(opts: HookOptions = {}): { installed: boolean; path: string; message: string } {
  const gitRoot = findGitRoot();
  if (!gitRoot) {
    return { installed: false, path: "", message: "Not a git repository." };
  }

  const hookPath = getHookPath(gitRoot);

  // Check for existing non-codegoat hook
  if (fs.existsSync(hookPath)) {
    const existing = fs.readFileSync(hookPath, "utf-8");
    if (!existing.includes(HOOK_MARKER)) {
      return {
        installed: false,
        path: hookPath,
        message: `Pre-commit hook already exists at ${hookPath}. Remove it first or add codegoat manually.`,
      };
    }
  }

  // Ensure hooks directory exists
  fs.mkdirSync(path.dirname(hookPath), { recursive: true });

  const script = generateHookScript(opts);
  fs.writeFileSync(hookPath, script, { mode: 0o755 });

  return {
    installed: true,
    path: hookPath,
    message: `Installed pre-commit hook at ${path.relative(gitRoot, hookPath)}`,
  };
}

export function uninstallHook(): { removed: boolean; path: string; message: string } {
  const gitRoot = findGitRoot();
  if (!gitRoot) {
    return { removed: false, path: "", message: "Not a git repository." };
  }

  const hookPath = getHookPath(gitRoot);

  if (!fs.existsSync(hookPath)) {
    return { removed: false, path: hookPath, message: "No pre-commit hook found." };
  }

  if (!isCodegoatHook(hookPath)) {
    return {
      removed: false,
      path: hookPath,
      message: "Pre-commit hook exists but was not installed by codegoat. Not removing.",
    };
  }

  fs.unlinkSync(hookPath);
  return {
    removed: true,
    path: hookPath,
    message: `Removed pre-commit hook from ${path.relative(gitRoot, hookPath)}`,
  };
}
